package ecv.tests;
import java.util.HashMap;
import java.util.Map;

import org.junit.After;
import org.junit.Before;
// Generated by Selenium IDE
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
public class AddDatosTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
	  System.setProperty( "webdriver.chrome.driver", "/Users/Alberto/Downloads/chromedriver");
	  driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void addDatosTest() throws InterruptedException {
    
	driver.get("http://localhost:8080/eCV/");
    driver.manage().window().setSize(new Dimension(1920, 1057));
    
    /**
     * LOGIN
     */
    driver.findElement(By.cssSelector("form:nth-child(1) > .headerButton")).click();
    // email = s
    driver.findElement(By.name("email")).click();
    driver.findElement(By.name("email")).sendKeys("s");
    // password = s
    driver.findElement(By.name("password")).click();
    driver.findElement(By.name("password")).sendKeys("s");
    driver.findElement(By.cssSelector(".logButton")).click();
    
    Thread.sleep(5000);
 
    
    /**
     * IMPORTAR DESDE ORCID
     */
    driver.findElement(By.id("connect-orcid-button")).click();
    vars.put("root", driver.getWindowHandle());
    String winHandleBefore = driver.getWindowHandle();
    Thread.sleep(12000);
//    driver.switchTo().window("vars.get(\"win7433\").toString()");
    for(String winHandle : driver.getWindowHandles()){
        driver.switchTo().window(winHandle);
    }
    driver.findElement(By.id("userId")).click();
    driver.findElement(By.id("userId")).sendKeys("martagqk@gmail.com");
    driver.findElement(By.id("password")).click();
    driver.findElement(By.id("password")).sendKeys("isst2019");
    driver.findElement(By.id("form-sign-in-button")).click();
    
    driver.close();
    
    driver.switchTo().window(winHandleBefore);
    
    /**
     * CAMBIAR NIVEL DE INGLES Y TEXTO LIBRE
     */
    driver.findElement(By.cssSelector(".orcidDiv > div:nth-child(3)")).click();
    driver.findElement(By.cssSelector("form:nth-child(3) > .menuButton")).click();
    driver.findElement(By.cssSelector("div:nth-child(8) input:nth-child(3)")).click();
    driver.findElement(By.cssSelector("div:nth-child(12) input:nth-child(3)")).click();
    driver.findElement(By.cssSelector("div:nth-child(12) input:nth-child(3)")).sendKeys("Ingles");
    driver.findElement(By.name("lst")).sendKeys("Alta");
    driver.findElement(By.name("rdg")).sendKeys("Media");
    driver.findElement(By.name("spk")).sendKeys("Alta");
    driver.findElement(By.cssSelector(".saveButton:nth-child(7)")).click();
    driver.findElement(By.cssSelector("form:nth-child(1) > .menuButton")).click();
    driver.findElement(By.name("freeText")).click();
    driver.findElement(By.name("freeText")).sendKeys("Esto es un texto de prueba");
    driver.findElement(By.cssSelector(".saveButton:nth-child(2)")).click();
    
    driver.close();
  }
}
