package ecv.tests;
// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.HashMap;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
public class DeleteCVtest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
	  System.setProperty( "webdriver.chrome.driver", "/Users/Alberto/Downloads/chromedriver");
	  driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void deleteCVtest() throws InterruptedException {
    driver.get("http://localhost:8080/eCV/");
    driver.manage().window().setSize(new Dimension(1920, 1057));
    
    /**
     * LOGIN
     */
    driver.findElement(By.cssSelector("form:nth-child(1) > .headerButton")).click();
    // email = a
    driver.findElement(By.name("email")).click();
    driver.findElement(By.name("email")).sendKeys("a");
    // password = a
    driver.findElement(By.name("password")).click();
    driver.findElement(By.name("password")).sendKeys("a");
    driver.findElement(By.cssSelector(".logButton")).click();
    
    Thread.sleep(5000);
    
    driver.findElement(By.cssSelector("form:nth-child(3) > .exportBttn")).click();
    driver.findElement(By.cssSelector("tr:nth-child(2) > td:nth-child(3) .removeButton")).click();
  }
}
