package ecv.tests;
import java.util.HashMap;
import java.util.Map;

import org.junit.After;
import org.junit.Before;
// Generated by Selenium IDE
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.interactions.Actions;

public class ExportarCVtest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
	  System.setProperty( "webdriver.chrome.driver", "/Users/Alberto/Downloads/chromedriver");
	  driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void exportarCVtest() throws InterruptedException {
	  driver.get("http://localhost:8080/eCV/");
	    driver.manage().window().setSize(new Dimension(1920, 1057));
	    driver.findElement(By.cssSelector("form:nth-child(1) > .headerButton")).click();
	    driver.findElement(By.name("email")).click();
	    driver.findElement(By.name("email")).sendKeys("s");
	    driver.findElement(By.name("password")).click();
	    driver.findElement(By.name("password")).sendKeys("s");
	    driver.findElement(By.cssSelector(".logButton")).click();
	    Thread.sleep(10000);
	    driver.findElement(By.cssSelector("form:nth-child(2) > .exportBttn")).click();
  }
}
